// src/user-wallet-token.controller.ts
// Controller for user wallet-based token creation (client-side signing)

import { Request, Response } from "express";
import { 
    createUnsignedTokenTransaction, 
    submitSignedTransaction 
} from './user-wallet-token.service.js';
import { 
    solanaTxUrl, 
    solscanTokenUrl, 
    solscanTxUrl 
} from './utils/solana-signature.js';
import { validateMetadataUri } from './metadata-validator.js';

interface CreateTokenWithUserWalletRequest {
    userPublicKey: string;  // User's wallet public key
    mintPublicKey: string;  // Mint account public key (pre-generated by client)
    name: string;
    symbol: string;
    uri: string;
    supply: string;
    decimals: string;
}

interface SubmitSignedTransactionRequest {
    signedTransaction: string;  // Base64 encoded signed transaction
    mintAddress?: string;        // Optional, for response enhancement
}

/**
 * Handler for creating unsigned token transaction
 * User will receive a serialized transaction to sign with their wallet
 */
export async function handleCreateUnsignedToken(
    req: Request<any, any, CreateTokenWithUserWalletRequest>, 
    res: Response
) {
    try {
        const { userPublicKey, mintPublicKey, name, symbol, uri, supply, decimals } = req.body;
        console.log("📥 Create unsigned token request:", req.body);

        // Validate required fields
        if (!userPublicKey || !mintPublicKey || !name || !symbol || !uri || !supply || !decimals) {
            return res.status(400).json({ 
                error: "Missing required fields: userPublicKey, mintPublicKey, name, symbol, uri, supply, or decimals." 
            });
        }

        // Validate metadata before creating transaction
        console.log("🔍 Validating metadata from URI...");
        const validationResult = await validateMetadataUri(uri, name, symbol);
        
        if (validationResult.warnings.length > 0) {
            console.warn("⚠️  Metadata validation warnings:");
            validationResult.warnings.forEach((warning, index) => {
                console.warn(`   ${index + 1}. ${warning}`);
            });
            
            // Check for critical errors
            const hasCriticalErrors = validationResult.warnings.some(w => 
                w.includes("not accessible") || 
                w.includes("not found") ||
                w.includes("Missing or invalid 'name'") ||
                w.includes("Missing or invalid 'symbol'")
            );
            
            if (hasCriticalErrors) {
                return res.status(400).json({
                    error: "Metadata validation failed",
                    warnings: validationResult.warnings,
                    recommendation: "Please ensure your metadata URI is accessible and contains valid 'name' and 'symbol' fields. Consider using /api/generate-metadata endpoint to create properly formatted metadata."
                });
            }
            
            console.log("⚠️  Continuing with transaction creation despite metadata warnings...");
        } else {
            console.log("✅ Metadata validation passed");
        }

        const tokenDetails = { name, symbol, uri, supply, decimals };
        
        // Create unsigned transaction
        const result = await createUnsignedTokenTransaction(userPublicKey, mintPublicKey, tokenDetails);
        
        const response: any = {
            success: true,
            message: result.message,
            transaction: result.transaction,
            mintAddress: result.mintAddress,
            instructions: [
                "1. The mint keypair was generated on your client and must be used to sign this transaction",
                "2. Sign the transaction with both the mint keypair and your user wallet",
                "3. Submit the signed transaction to /api/submit-signed-transaction",
                "4. The token will be created and minted to your wallet"
            ],
            network: 'devnet',
            solscanTokenLink: solscanTokenUrl(result.mintAddress, 'devnet')
        };
        
        // Include warnings if metadata had issues
        if (validationResult.warnings.length > 0) {
            response.warnings = validationResult.warnings;
            response.note = "Transaction created successfully, but metadata may not display properly on Solscan due to the warnings above. Consider using /api/generate-metadata endpoint for properly formatted metadata.";
        }
        
        res.status(200).json(response);

    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
        // Log error type without sensitive details
        console.error(`❌ Error creating unsigned token transaction: ${error instanceof Error ? error.constructor.name : 'Unknown'}`);
        res.status(500).json({ 
            error: errorMessage, 
            details: "An error occurred during unsigned transaction creation." 
        });
    }
}

/**
 * Handler for submitting signed transaction
 * User submits the transaction they signed with their wallet
 */
export async function handleSubmitSignedTransaction(
    req: Request<any, any, SubmitSignedTransactionRequest>, 
    res: Response
) {
    try {
        const { signedTransaction, mintAddress } = req.body;
        console.log("📥 Submit signed transaction request received");

        // Validate required fields
        if (!signedTransaction) {
            return res.status(400).json({ 
                error: "Missing required field: signedTransaction" 
            });
        }

        // Submit the signed transaction
        const result = await submitSignedTransaction(signedTransaction);
        
        const response: any = {
            success: true,
            message: result.message,
            transactionSignature: result.signature,
            explorerLink: solanaTxUrl(result.signature, 'devnet'),
            solscanTxLink: solscanTxUrl(result.signature, 'devnet')
        };
        
        // Add mint address links if provided
        if (mintAddress) {
            response.mintAddress = mintAddress;
            response.solscanTokenLink = solscanTokenUrl(mintAddress, 'devnet');
        }
        
        res.status(200).json(response);

    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
        // Log error type without sensitive details
        console.error(`❌ Error submitting signed transaction: ${error instanceof Error ? error.constructor.name : 'Unknown'}`);
        res.status(500).json({ 
            error: errorMessage, 
            details: "An error occurred while submitting the signed transaction." 
        });
    }
}
